<div class="header-line">
    <ul class="header-line-content">
        <li class="free-delivery">Free Delivery<br><span>on orders over $100</span></li>
        <svg width="1" height="17">
            <rect width="1" height="17" style="fill:#ffffff;"></rect>
        </svg>
        <li class="free-gift">Choose a Free Gift<br><span>with every purchase</span></li>
        <svg width="1" height="17">
            <rect width="1" height="17" style="fill:#ffffff;"></rect>
        </svg>
        <li class="secure-shopping">100% Secure Shopping<br><span>mauric ac pulvinar</span></li>
    </ul>
</div>
