<li class="level0  level-top category-item"><a class="level-top" href="#">Fashion</a></li>
<li class="level0 level-top category-item"><a class="level-top" href="#">Electronics</a>
    <ul class="level0 submenu megamenu">
        <div class="megamenu-content">
            <div class="submenu-flex">
                <div class="submenu-pic"></div>
                <li class="level0 level-top category-item"><a class="level-top" href="#">Mobile</a>
                    <ul class="megamenu-list">
                        <li><a class="level-top" href="#">Phones</a></li>
                        <li><a class="level-top" href="#">Tablets</a></li>
                        <li><a class="level-top" href="#">Wearables</a></li>
                        <li><a class="level-top" href="#">Virtual Reality</a></li>
                        <li><a class="level-top" href="#">Audio</a></li>
                        <li><a class="level-top" href="#">Accessories</a></li>
                    </ul>
                </li>
            </div>
            <div class="submenu-flex">
                <div class="submenu-pic"></div>
                <li class="level0 level-top category-item"><a class="level-top" href="#">Cameras</a>
                    <ul class="megamenu-list">
                        <li><a class="level-top" href="#">MP3 Players</a></li>
                        <li><a class="level-top" href="#">Format Shoes</a></li>
                        <li><a class="level-top" href="#">Casual Shoes</a></li>
                        <li><a class="level-top" href="#">Sandals</a></li>
                        <li><a class="level-top" href="#">Boots</a></li>
                        <li><a class="level-top" href="#">Slippers</a></li>
                    </ul>
                </li>
            </div>
            <div class="submenu-flex">
                <div class="submenu-pic"></div>
                <li class="level0 level-top category-item"><a class="level-top" href="#">Televisions</a>
                    <ul class="megamenu-list">
                        <li><a class="level-top" href="#">Televisions</a></li>
                        <li><a class="level-top" href="#">Home Theater</a></li>
                        <li><a class="level-top" href="#">Sound Bars</a></li>
                        <li><a class="level-top" href="#">Projectors</a></li>
                        <li><a class="level-top" href="#">Blu-ray Players</a></li>
                        <li><a class="level-top" href="#">DVD Players</a></li>
                    </ul>
                </li>
            </div>
            <div class="submenu-flex">
                <div class="submenu-pic"></div>
                <li class="level0 level-top category-item"><a class="level-top" href="#">Computing</a>
                    <ul class="megamenu-list">
                        <li><a class="level-top" href="#">MP3 Players</a></li>
                        <li><a class="level-top" href="#">Format Shoes</a></li>
                        <li><a class="level-top" href="#">Casual Shoes</a></li>
                        <li><a class="level-top" href="#">Sandals</a></li>
                        <li><a class="level-top" href="#">Boots</a></li>
                        <li><a class="level-top" href="#">Slippers</a></li>
                    </ul>
                </li>
            </div>
            <div class="submenu-flex">
                <div class="submenu-pic"></div>
                <li class="level0 level-top category-item"><a class="level-top" href="#">Home Appliances</a>
                    <ul class="megamenu-list">
                        <li><a class="level-top" href="#">Refrigerators</a></li>
                        <li><a class="level-top" href="#">Ranges</a></li>
                        <li><a class="level-top" href="#">Cooktops & Hoods</a></li>
                        <li><a class="level-top" href="#">Microwaves</a></li>
                        <li><a class="level-top" href="#">Dishwashers</a></li>
                        <li><a class="level-top" href="#">Washers</a></li>
                    </ul>
                </li>
            </div>
        </div>
        <div class="megamenu-bottom">
            <div>
                <h1>Intelligent<br>User Interface</h1>
                <p>Starting at <span>$240</span></p>
            </div>
            <div>
                <p>Home Appliances</p>
                <h1>Efficient In<br>Every Way</h1>
            </div>
            <div>
                <div class="box arrow-bottom">
                    <p class="price-old">$1500.00</p>
                    <p class="price-text"><span class="dollar-sign">$</span>1100<sup>.00</sup></p>
                </div>
                <p>Windows Laptops</p>
                <h1>Immersive &<br>Adaptable</h1>

            </div>
        </div>
    </ul>
</li>
<li class="level0 level-top category-item"><a class="level-top" href="#">Gifts</a></li>
<li class="level0 level-top category-item"><a class="level-top" href="#">Books</a></li>
<li class="level0 level-top category-item"><a class="level-top" href="#">At Home</a></li>
<li class="level0 level-top category-item"><a class="level-top" href="#">Music</a></li>
